import { useState } from 'react';
const createComplaintId = () => `CMP-${Date.now().toString().slice(-6)}`;

function CustomerServiceExecutive() {
	const [activeTab, setActiveTab] = useState('raise');
	const [complaintId, setComplaintId] = useState(createComplaintId);
	const [complaints, setComplaints] = useState([]);

	const handleSubmit = (event) => {
		event.preventDefault();
		const formData = new FormData(event.currentTarget);
		const complaint = Object.fromEntries(formData.entries());

		setComplaints((currentComplaints) => [complaint, ...currentComplaints]);
		setComplaintId(createComplaintId());
		event.currentTarget.reset();
		setActiveTab('list');
	};

	return (
		<main className="role-main">
			<section className="role-panel role-panel-coral complaint-panel" aria-labelledby="complaint-form-title">
				<div className="complaint-heading">
					<div className="role-copy">
						<p className="eyebrow">Customer service executive</p>
						<h1 id="complaint-form-title">Raise the complaint</h1>
					</div>
					<span className="complaint-count">{complaints.length} raised</span>
				</div>

				<div className="complaint-tabs" role="tablist" aria-label="Complaint workspace">
					<button className={activeTab === 'raise' ? 'tab-button active' : 'tab-button'} type="button" role="tab" aria-selected={activeTab === 'raise'} onClick={() => setActiveTab('raise')}>Raise Complaint</button>
					<button className={activeTab === 'list' ? 'tab-button active' : 'tab-button'} type="button" role="tab" aria-selected={activeTab === 'list'} onClick={() => setActiveTab('list')}>Complaint List</button>
				</div>

				{activeTab === 'raise' ? <form className="complaint-form" onSubmit={handleSubmit}>
					<div className="form-field">
						<label htmlFor="complaint-id">Complaint ID</label>
						<input id="complaint-id" name="complaintId" type="text" value={complaintId} readOnly />
						<span className="field-hint">Auto-generated by CCMS</span>
					</div>
					<div className="form-field">
						<label htmlFor="customer-name">Customer Name</label>
						<input id="customer-name" name="customerName" type="text" placeholder="Enter customer name" required />
					</div>
					<div className="form-field">
						<label htmlFor="customer-email">Customer Email</label>
						<input id="customer-email" name="customerEmail" type="email" placeholder="name@example.com" required />
					</div>
					<div className="form-field">
						<label htmlFor="mobile-number">Mobile Number</label>
						<input id="mobile-number" name="mobileNumber" type="tel" placeholder="Enter mobile number" required />
					</div>
					<div className="form-field form-field-wide">
						<label htmlFor="complaint-title">Complaint Title</label>
						<input id="complaint-title" name="complaintTitle" type="text" placeholder="Summarize the complaint" required />
					</div>
					<div className="form-field form-field-wide">
						<label htmlFor="complaint-description">Complaint Description</label>
						<textarea id="complaint-description" name="complaintDescription" rows="5" placeholder="Describe the complaint in detail" required />
					</div>
					<div className="form-field">
						<label htmlFor="complaint-date">Complaint Date</label>
						<input id="complaint-date" name="complaintDate" type="date" defaultValue={new Date().toISOString().split('T')[0]} required />
					</div>
					<div className="form-actions">
						<button type="submit">Create complaint</button>
					</div>
				</form> : <div className="complaint-list" role="tabpanel">
					{complaints.length === 0 ? <div className="empty-list"><span className="empty-list-icon" aria-hidden="true">+</span><strong>No complaints raised yet</strong><span>New complaints will appear here after submission.</span><button type="button" onClick={() => setActiveTab('raise')}>Raise your first complaint</button></div> : <div className="complaint-items">{complaints.map((complaint) => <article className="complaint-item" key={complaint.complaintId}>
						<div className="complaint-item-top"><span className="complaint-id">{complaint.complaintId}</span><time dateTime={complaint.complaintDate}>{complaint.complaintDate}</time></div>
						<h2>{complaint.complaintTitle}</h2><p>{complaint.complaintDescription}</p>
						<div className="complaint-item-meta"><span>{complaint.customerName}</span><span>{complaint.customerEmail}</span><span>{complaint.mobileNumber}</span></div>
					</article>)}</div>}
				</div>}
			</section>
		</main>
	);
}

export default CustomerServiceExecutive;
